### PR TITLE
dedicatedhost Edit and show tags

### PR DESCRIPTION
**Pull request by yhuanghamu**
1. Add new cli command to edit tags of dedicatedhost
2. Show tags in dedicatedhost detail
3. Filtered dedicatedhost via tag
e.g.
```
slcli dedicatedhost edit --tag nicetag 258803
slcli --format=json dedicatedhost detail 258803
{
    "modify date": "",
    "hostname": "dev-ryans-cluster0650-cluster-service-compute0-0",
    "cpu count": 56,
    "router hostname": "bcr01a.dal10",
    "memory capacity": 242,
    "tags": [
        "nicetag"
    ],
    "disk capacity": 1200,
    "guest count": 0,
    "create date": "2018-10-10T12:46:35-06:00",
    "router id": 843613,
    "owner": "1703415_mark+ibmdev@rescale.com_2018-08-02-13.24.01",
    "datacenter": "dal10",
    "id": 258803
}
```

### CODE REVIEW

**Comment by yhuanghamu** [comment]
slcli dedicatedhost edit --tag nicetag,goodtag 258803

	    "tags": [
        "nicetag", 
        "goodtag"
    ],

**Comment by yhuanghamu** [comment]
```
slcli --format=json dedicatedhost list --tag nicetag
[
    {
        "datacenter": "dal10", 
        "memoryCapacity": 242, 
        "name": "dev-ryans-cluster0650-cluster-service-compute0-0", 
        "diskCapacity": 1200, 
        "guestCount": null, 
        "cpuCount": 56, 
        "id": 258803
    }
]
```
and
```
slcli --format=json dedicatedhost list --tag badtag 
[]
```

**Comment by yhuanghamu** [comment]
Hmm, dedicatedhost cancellation need to updated as well, will look into it
this morning

**Comment by yhuanghamu** [comment]
@kramimus Could you retest it?

**Comment by yhuanghamu** [comment]
Dedicated cancel will call `get_host` method with `mask` that only return billing id , KeyError will be raised in that case.

**Comment by yhuanghamu** [comment]
```
> slcli dedicatedhost cancel 261603 
> slcli dedicatedhost list         
:....:..........:..........:..............:................:............:............:
: id : hostname : cpuCount : diskCapacity : memoryCapacity : datacenter : guestCount :
:....:..........:..........:..............:................:............:............:
:....:..........:..........:..............:................:............:............:

```

**Comment by kramimus** [comment]
Yeah, this looks good

**Pull request merged**
