### PR TITLE
Remove more junk from dedicatedhost cancel command

### PR DESCRIPTION
**Pull request by kramimus**
not sure what resolve_ids function was doing besides throwing exceptions but cancel seems to work fine without it

### CODE REVIEW

**Comment by yhuanghamu** [comment]
Just test it, dedicated host got cancelled.
But got this exception
```
SoftLayerAPIError(SoftLayer_Exception_ObjectNotFound): Unable to find object with id of '251903'.
```

**Comment by yhuanghamu** [comment]
Also, i think you fix another hidden bug. 
If we forgot to add `--immeidate` option, if will become strand hosts. Guess the exception from `resolve-id` stop us from cancel it again.
guess you could remove same thing in``` hardware cancel ``` as well

**Comment by kramimus** [comment]
Ok, I looked at the resolve_id code some more and now am confused why there were ever errors being thrown. It looks like utils.resolve_ids should be getting called and if that is the case, if the "ID" passed is just an int, it should pass straight through without any "resolving"

**Comment by kramimus** [comment]
Looks like the last get_host is superfluous and when running it through the debugger, found to be the cause of the exception.

This was mistakenly left in when copy the managers/hardware.py cancel code over. It looks like for bare metal, cancellation is a 2 step process which needed to reload the host ID after the first step of the cancellation. Cancelling VSIs and dedicatedhosts is just the single API call.

**Pull request merged**
