### PR TITLE
Pull hostIds upon creation of a dedicatedhost

### PR DESCRIPTION
**Pull request by kramimus**
After creating a dedicatedhost, poll for all hostIds with a matching orderId
by listing all dedicatedhosts and filtering by new order_id

### CODE REVIEW

**Comment by yhuanghamu** [comment]
1. First test, auto abort my request
slcli dedicatedhost create --hostname "test-Pr1" --domain rescale.com --datacenter wdc07 --flavor 56_CORES_X_242_RAM_X_1_4_TB

This action will incur charges on your account. Continue? [y/N]: Aborting dedicated host order.

Not sure it is stable or not.

**Comment by yhuanghamu** [comment]
Yeah. Make another request in CLI, It is not stable. It auto aborted twice and 
Since we have retry strategy in clusterservice#softlayerclient, it should be fine.

**Comment by yhuanghamu** [comment]
> mine have all gone through (like 4-5), so there are no error msgs when it aborts?

This action will incur charges on your account. Continue? [y/N]: Aborting dedicated host order.

This is the error message with CLI.

**Comment by kramimus** [comment]
:sadpanda:

**Pull request merged**
